"""Section-by-section MIDI-to-LilyPond generation orchestration.

Loads a MIDI file, analyzes its musical properties, detects section
boundaries, generates LilyPond per section via LLM, compiles through
the fix loop, and assembles the complete output.  Generation halts on
first unrecoverable compilation failure.

Parallel fan-out: each section dispatches two concurrent LLM requests --
one for LilyPond (existing), one for structured JSON notation events
(new).  JSON generation is optional; failure does not affect LilyPond.

Section-group dispatch (Phase 7): instruments sharing a ``section_group``
(e.g. 4 trumpets) are generated by a single LLM call.  This reduces
big-band dispatch from 17 calls to 7 per temporal section (3 section
groups + 4 individual rhythm instruments) while enabling convergent
sight-reading -- musicians in a section independently arrive at the
same interpretation.

Post-processing pipeline order::

    LLM output -> ENSM-03 defaults -> ENSM-05 omission -> final LilyPond
"""

from __future__ import annotations

import asyncio
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from engrave.generation.assembler import assemble_sections
from engrave.generation.audit import AuditLog, FieldResolution
from engrave.generation.coherence import CoherenceState
from engrave.generation.failure_log import FailureRecord
from engrave.generation.prompts import (
    build_json_generation_suffix,
    build_section_prompt,
    extract_json_from_response,
)
from engrave.generation.templates import (
    build_instrument_variable,
    build_score_template,
    parse_instrument_blocks,
    sanitize_var_name,
    strip_variable_wrapper,
)
from engrave.lilypond.fixer import compile_with_fix_loop, extract_lilypond_from_response
from engrave.midi.analyzer import MidiAnalysis, analyze_midi
from engrave.midi.loader import MidiTrackInfo, load_midi
from engrave.midi.sections import detect_sections
from engrave.midi.tokenizer import tokenize_section_for_prompt

if TYPE_CHECKING:
    from engrave.audio.description import AudioDescription
    from engrave.generation.validation import ValidationResult
    from engrave.lilypond.compiler import LilyPondCompiler
    from engrave.llm.router import InferenceRouter
    from engrave.rendering.ensemble import BigBandPreset

logger = logging.getLogger(__name__)


class GenerationHaltError(Exception):
    """Raised when a section fails compilation after all retries.

    Attributes:
        section_index: The zero-based index of the section that failed.
        final_errors: List of error strings from the last compilation attempt.
        attempt_count: Total number of fix attempts made.
    """

    def __init__(
        self,
        section_index: int,
        final_errors: list[str],
        attempt_count: int,
    ) -> None:
        self.section_index = section_index
        self.final_errors = final_errors
        self.attempt_count = attempt_count
        super().__init__(
            f"Generation halted at section {section_index}: "
            f"{len(final_errors)} errors after {attempt_count} attempts"
        )


@dataclass
class GenerationResult:
    """Result of a complete MIDI-to-LilyPond generation run."""

    success: bool
    ly_source: str = ""  # Complete assembled .ly file or empty on failure
    sections_completed: int = 0
    total_sections: int = 0
    failure_record: FailureRecord | None = None
    instrument_names: list[str] = field(default_factory=list)
    json_sections: list[list[dict] | None] = field(default_factory=list)
    validation: ValidationResult | None = None


def _build_instrument_names(
    tracks: list[MidiTrackInfo],
    user_labels: dict[int, str] | None = None,
) -> list[str]:
    """Build instrument name list from tracks, with optional user overrides.

    Args:
        tracks: Loaded MIDI tracks.
        user_labels: Optional mapping of track_index -> instrument name.

    Returns:
        List of instrument names, one per track.
    """
    names: list[str] = []
    has_ambiguous = False

    for track in tracks:
        if user_labels and track.track_index in user_labels:
            names.append(user_labels[track.track_index])
        elif track.instrument_name:
            names.append(track.instrument_name)
        else:
            has_ambiguous = True
            names.append(f"Part {track.track_index + 1}")

    if has_ambiguous and not user_labels:
        logger.warning(
            "Some tracks lack instrument metadata. Using generic names. "
            "Provide user_labels for better results."
        )

    return names


def _extract_analysis_properties(analysis: MidiAnalysis) -> tuple[str, str, int]:
    """Extract key_signature, time_signature, and tempo_bpm from analysis.

    MidiAnalysis stores these as lists; we extract the first/primary values.

    Returns:
        (key_signature, time_signature_str, tempo_bpm)
    """
    key_sig = analysis.key_signature

    # Time signature: first entry as "N/D" string
    if analysis.time_signatures:
        num, denom, _tick = analysis.time_signatures[0]
        time_sig = f"{num}/{denom}"
    else:
        num, denom = 4, 4
        time_sig = "4/4"

    # Tempo: first entry's BPM
    tempo_bpm = int(analysis.tempo_changes[0][0]) if analysis.tempo_changes else 120

    return key_sig, time_sig, tempo_bpm


def _filter_notes_for_section(
    track: MidiTrackInfo,
    start_bar: int,
    end_bar: int,
    ticks_per_beat: int,
    beats_per_bar: float,
) -> list:
    """Filter a track's notes to those within a section's bar range."""
    ticks_per_bar = int(ticks_per_beat * beats_per_bar)
    start_tick = (start_bar - 1) * ticks_per_bar
    end_tick = end_bar * ticks_per_bar

    return [n for n in track.notes if n.start_tick >= start_tick and n.start_tick < end_tick]


async def _request_json_notation(
    messages: list[dict[str, str]],
    instrument_names: list[str],
    router: InferenceRouter,
) -> list[dict] | None:
    """Dispatch the JSON notation generation request.

    Reuses the prefix messages (system, shared user, assistant) from the
    LilyPond prompt and replaces the last user message with JSON instructions.
    This maximizes prefix cache hits on vllm-mlx.

    Isolated so that any failure is caught without affecting LilyPond.

    Returns:
        Parsed JSON notation events, or None on any failure.
    """
    json_suffix = build_json_generation_suffix(instrument_names)
    # Replace last user message content with JSON variant
    json_messages = [m.copy() for m in messages]
    json_messages[-1] = {
        "role": "user",
        "content": messages[-1]["content"] + "\n\n" + json_suffix,
    }
    try:
        json_response = await router.complete(
            role="generator",
            messages=json_messages,
            temperature=0.1,
        )
        result = extract_json_from_response(json_response)
        return result if result else None
    except Exception:
        logger.warning("JSON notation generation failed; continuing with LilyPond only")
        return None


async def generate_section(
    section_midi: dict[str, str],
    coherence: CoherenceState,
    rag_examples: list[str],
    template: str,
    instrument_names: list[str],
    router: InferenceRouter,
    compiler: LilyPondCompiler,
    audio_description: str = "",
    user_hints: str = "",
) -> tuple[str, list[dict] | None, CoherenceState]:
    """Generate LilyPond (and optionally JSON) for a single section.

    Fans out two concurrent LLM requests via asyncio.gather:
      1. LilyPond generation (temperature 0.3, existing behaviour)
      2. JSON notation events (temperature 0.1, new)

    JSON failure does **not** affect the LilyPond path.

    Args:
        section_midi: Dict mapping track name to tokenized MIDI text.
        coherence: Current musical context state.
        rag_examples: Retrieved LilyPond examples from corpus.
        template: LilyPond structural template for this section.
        instrument_names: List of instrument names.
        router: LLM inference router.
        compiler: LilyPond compiler for fix loop.
        audio_description: Rendered NL text for this section (CONTEXTUAL block).
        user_hints: Raw user hint text (DEFINITIVE block).

    Returns:
        Tuple of (section_ly_source, json_notation_or_none, updated_coherence).

    Raises:
        GenerationHaltError: If compilation fails after all retries.
    """
    # Build shared prompt as multi-message list (optimized for prefix caching)
    messages = build_section_prompt(
        section_midi,
        coherence,
        rag_examples,
        template,
        audio_description=audio_description,
        user_hints=user_hints,
    )

    # LilyPond first (critical path — feeds compile-fix loop), then JSON.
    # Sequential within each group keeps total active LLM requests equal to
    # max_concurrent_groups (8) instead of 2x that (16), preventing vllm-mlx
    # OOM from KV cache pressure.
    ly_response = await router.complete(
        role="generator",
        messages=messages,
        temperature=0.3,
    )
    json_data = await _request_json_notation(messages, instrument_names, router)

    # -- LilyPond processing (unchanged) ----------------------------------

    # Extract LilyPond from response (handles code blocks etc.)
    extracted = extract_lilypond_from_response(ly_response)

    # Parse instrument blocks from LLM response
    try:
        blocks = parse_instrument_blocks(extracted)
    except ValueError:
        # If parsing fails, try the raw response
        try:
            blocks = parse_instrument_blocks(ly_response)
        except ValueError:
            # Fall back to using the extracted content as a single block
            var_names = [sanitize_var_name(name) for name in instrument_names]
            blocks = {var_names[0]: extracted} if var_names else {}

    # Fill template variables with extracted music content
    var_declarations = []
    for name in instrument_names:
        var_name = sanitize_var_name(name)
        content = blocks.get(var_name, "R1")  # Rest if LLM didn't provide
        content = strip_variable_wrapper(var_name, content)
        var_declarations.append(build_instrument_variable(var_name, content))

    # Build section source from template with filled variables
    section_source = _build_section_source(instrument_names, var_declarations, coherence)

    # Compile through fix loop
    compile_result = await compile_with_fix_loop(
        source=section_source,
        router=router,
        compiler=compiler,
    )

    if not compile_result.success:
        return section_source, json_data, coherence

    # Update coherence with compiled source
    midi_text = "\n".join(section_midi.values())
    updated_coherence = coherence.update_from_section(compile_result.source, midi_text)

    return compile_result.source, json_data, updated_coherence


def _build_section_source(
    instrument_names: list[str],
    var_declarations: list[str],
    coherence: CoherenceState,
) -> str:
    """Build a compilable section source from variable declarations.

    Args:
        instrument_names: List of instrument names.
        var_declarations: List of formatted variable declaration strings.
        coherence: Current coherence state for tempo/key info.

    Returns:
        Complete LilyPond source string for this section.
    """
    var_names = [sanitize_var_name(name) for name in instrument_names]

    # Build staff references
    staff_lines = []
    for var_name, inst_name in zip(var_names, instrument_names, strict=True):
        staff_lines.append(
            f'    \\new Staff \\with {{ instrumentName = "{inst_name}" }} \\{var_name}'
        )

    staves_block = "\n".join(staff_lines)
    variables_block = "\n\n".join(var_declarations)

    return (
        f'\\version "2.24.0"\n'
        f"\n"
        f"% Generated by Engrave - concert pitch\n"
        f"\n"
        f"{variables_block}\n"
        f"\n"
        f"\\score {{\n"
        f"  <<\n"
        f"{staves_block}\n"
        f"  >>\n"
        f"  \\layout {{ }}\n"
        f"}}\n"
    )


def _save_training_pair(
    ly_source: str,
    json_data: list[dict],
    section_index: int,
    output_dir: str,
) -> None:
    """Save an aligned (LilyPond, JSON) training pair to the job directory.

    The pair is written as a single JSON file containing both the LilyPond
    source and the structured notation events for future fine-tuning data.

    Args:
        ly_source: LilyPond source string for this section.
        json_data: Parsed JSON notation events for this section.
        section_index: Zero-based section index (used in filename).
        output_dir: Root output/job directory path.
    """
    pairs_dir = Path(output_dir) / "training_pairs"
    pairs_dir.mkdir(parents=True, exist_ok=True)
    pair_path = pairs_dir / f"section_{section_index}.json"
    pair = {
        "ly_source": ly_source,
        "json_notation": json_data,
    }
    pair_path.write_text(json.dumps(pair, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.debug("Saved training pair: %s", pair_path)


def _write_audit_log(audit_log: AuditLog, output_dir: str | None) -> None:
    """Write audit log to the output directory if one is available."""
    if output_dir is not None:
        try:
            audit_log.write(Path(output_dir))
        except Exception:
            logger.warning("Failed to write audit log")


# ---------------------------------------------------------------------------
# Section-group resolution helpers
# ---------------------------------------------------------------------------


def _resolve_generation_groups(
    instrument_names: list[str],
    tracks: list[MidiTrackInfo],
    preset: BigBandPreset | None,
) -> list[list[tuple[str, MidiTrackInfo]]]:
    """Resolve instruments into generation groups based on preset section_group.

    When a preset is provided, instruments are matched by name to specs and
    grouped by section_group.  Without a preset, each instrument forms its
    own single-element group (backward-compatible per-instrument dispatch).

    Returns:
        List of groups; each group is a list of (instrument_name, track) tuples.
    """
    if preset is None:
        # No preset: each instrument is its own generation group
        return [[(name, track)] for name, track in zip(instrument_names, tracks, strict=True)]

    from engrave.generation.section_groups import resolve_section_groups

    groups = resolve_section_groups(preset.instruments)

    # Build a lookup: variable_name -> (instrument_name, track)
    var_to_info: dict[str, tuple[str, MidiTrackInfo]] = {}
    for name, track in zip(instrument_names, tracks, strict=True):
        var_name = sanitize_var_name(name)
        var_to_info[var_name] = (name, track)

    result: list[list[tuple[str, MidiTrackInfo]]] = []
    for group in groups:
        group_items: list[tuple[str, MidiTrackInfo]] = []
        for spec in group:
            if spec.variable_name in var_to_info:
                group_items.append(var_to_info[spec.variable_name])
        if group_items:
            result.append(group_items)

    return result


def _group_identifier(group: list[tuple[str, object]]) -> str:
    """Return a stable identifier for a generation group.

    For multi-instrument groups this is the first instrument name (the section lead).
    For single-instrument groups it is the instrument's variable name.
    """
    if len(group) == 1:
        return sanitize_var_name(group[0][0])
    return sanitize_var_name(group[0][0])


@dataclass
class _GroupResult:
    """Result of processing a single generation group within a section."""

    gid: str
    group_names: list[str]
    success: bool
    blocks: dict[str, str]  # var_name -> music content
    json_data: list[dict] | None
    updated_coherence: CoherenceState | None
    used_fallback: bool


async def _process_group(
    group: list[tuple[str, MidiTrackInfo]],
    coherence: CoherenceState,
    sec_idx: int,
    start_bar: int,
    end_bar: int,
    ticks_per_beat: int,
    beats_per_bar: float,
    time_sig_tuple: tuple[int, int],
    key_sig: str,
    tempo_bpm: int,
    beam_cmds: str,
    section_label: str,
    router: InferenceRouter,
    compiler: LilyPondCompiler,
    rag_retriever: object | None,
    audio_description: AudioDescription | None,
    user_hints: str,
    semaphore: asyncio.Semaphore,
) -> _GroupResult:
    """Process a single generation group (concurrency-safe).

    Acquires a semaphore slot before dispatching the LLM request.
    All state is local to the group; no cross-group mutation.
    """
    async with semaphore:
        gid = _group_identifier(group)
        group_names = [name for name, _track in group]
        logger.info("  Group '%s': %s", gid, group_names)

        # Filter and tokenize notes scoped to this group
        group_midi: dict[str, str] = {}
        for name, track in group:
            filtered_notes = _filter_notes_for_section(
                track, start_bar, end_bar, ticks_per_beat, beats_per_bar
            )
            tokens = tokenize_section_for_prompt(
                notes=filtered_notes,
                time_sig=time_sig_tuple,
                key=key_sig,
                bars=(start_bar, end_bar),
                ticks_per_beat=ticks_per_beat,
            )
            group_midi[name] = tokens

        # Query RAG scoped to group instruments
        rag_examples: list[str] = []
        if rag_retriever is not None:
            query = f"{key_sig} {tempo_bpm}bpm {', '.join(group_names)}"
            try:
                rag_examples = rag_retriever(query, limit=3)
            except Exception:
                logger.warning("RAG retrieval failed for group %s", gid)
                rag_examples = []

        # Build template with beaming commands injected
        template = build_score_template(
            group_names, section_label, start_bar, end_bar, beaming=beam_cmds
        )

        # Generate for this group
        group_generation_ok = True
        updated_coherence: CoherenceState | None = coherence
        json_data: list[dict] | None = None
        group_source = ""
        try:
            group_source, json_data, updated_coherence = await generate_section(
                section_midi=group_midi,
                coherence=coherence,
                rag_examples=rag_examples,
                template=template,
                instrument_names=group_names,
                router=router,
                compiler=compiler,
                audio_description=_render_section_audio_text(
                    audio_description, sec_idx, start_bar, end_bar
                ),
                user_hints=user_hints,
            )
        except Exception as exc:
            logger.error("Generation failed for group '%s': %s", gid, exc)
            group_generation_ok = False

        # Check if compilation succeeded (coherence advanced)
        if (
            group_generation_ok
            and updated_coherence is not None
            and updated_coherence.section_index <= coherence.section_index
        ):
            logger.error(
                "Compilation FAILED for group '%s' in section %d (coherence did not advance)",
                gid,
                sec_idx,
            )
            group_generation_ok = False

        # Fallback: fill failed group with rests
        if not group_generation_ok:
            num_bars = max(1, end_bar - start_bar + 1)
            rest_duration = f"R{time_sig_tuple[1]}" if time_sig_tuple[1] != 1 else "R1"
            rest_content = f"{rest_duration}*{num_bars}"
            logger.warning(
                "Using rest fallback for group '%s' section %d (%d bars)",
                gid,
                sec_idx,
                num_bars,
            )
            blocks: dict[str, str] = {}
            for name in group_names:
                var_name = sanitize_var_name(name)
                blocks[var_name] = rest_content
            return _GroupResult(
                gid=gid,
                group_names=group_names,
                success=False,
                blocks=blocks,
                json_data=None,
                updated_coherence=None,
                used_fallback=True,
            )

        # Extract variable contents from group source
        blocks = {}
        for name in group_names:
            var_name = sanitize_var_name(name)
            content = _extract_var_content(group_source, var_name)
            blocks[var_name] = content

        return _GroupResult(
            gid=gid,
            group_names=group_names,
            success=True,
            blocks=blocks,
            json_data=json_data,
            updated_coherence=updated_coherence,
            used_fallback=False,
        )


async def generate_from_midi(
    midi_path: str,
    router: InferenceRouter,
    compiler: LilyPondCompiler,
    rag_retriever=None,
    user_labels: dict[int, str] | None = None,
    output_dir: str | None = None,
    audio_description: AudioDescription | None = None,
    user_hints: str = "",
    preset: BigBandPreset | None = None,
    max_concurrent_groups: int = 8,
) -> GenerationResult:
    """Orchestrate end-to-end MIDI-to-LilyPond generation.

    1. Load and normalize MIDI
    2. Analyze musical properties
    3. Detect section boundaries
    4. For each temporal section:
       a. Resolve section groups from preset
       b. Dispatch groups concurrently via asyncio.gather (Semaphore-bounded)
       c. Apply ENSM-03 articulation defaults + ENSM-05 section consistency
       d. Inject beaming commands per temporal section
    5. Assemble all sections into complete .ly file
    6. Write audit log

    Args:
        midi_path: Path to the input MIDI file.
        router: LLM inference router.
        compiler: LilyPond compiler.
        rag_retriever: Optional RAG retriever callable (query, limit) -> list[str].
        user_labels: Optional track_index -> instrument_name overrides.
        output_dir: Optional job output directory.  When provided, aligned
            (LilyPond, JSON) training pairs are saved under
            ``output_dir/training_pairs/``.
        audio_description: Optional AudioDescription from audio LM.
        user_hints: Raw user hint text (full block goes to every section).
        preset: Optional BigBandPreset for section-group dispatch.  When
            provided, instruments sharing a ``section_group`` are generated
            by a single LLM call.  When ``None``, falls back to per-instrument
            generation (backward compatible).
        max_concurrent_groups: Maximum concurrent LLM group dispatches per
            section.  Matches vllm-mlx slot count (default 8).

    Returns:
        GenerationResult with success status and output.
    """
    # 1. Load MIDI
    tracks, _metadata = load_midi(midi_path)
    if not tracks:
        logger.error("No tracks found in MIDI file: %s", midi_path)
        return GenerationResult(success=False, total_sections=0)

    # 2. Analyze musical properties
    analysis = analyze_midi(midi_path)

    # 3. Build instrument names
    instrument_names = _build_instrument_names(tracks, user_labels)

    # 4. Extract analysis properties
    key_sig, time_sig_str, tempo_bpm = _extract_analysis_properties(analysis)

    # Parse time signature for tokenizer
    ts_parts = time_sig_str.split("/")
    time_sig_tuple = (int(ts_parts[0]), int(ts_parts[1]))
    beats_per_bar = time_sig_tuple[0] * (4.0 / time_sig_tuple[1])

    # 5. Detect sections
    sections = detect_sections(midi_path)
    total_sections = len(sections)
    logger.info(
        "Loaded %d tracks, %d sections, key=%s, tempo=%d, time=%s",
        len(tracks),
        total_sections,
        key_sig,
        tempo_bpm,
        time_sig_str,
    )
    logger.info("Instruments: %s", instrument_names)

    # 6. Initialize per-group coherence state
    class _AnalysisProxy:
        pass

    proxy = _AnalysisProxy()
    proxy.key_signature = key_sig  # type: ignore[attr-defined]
    proxy.time_signature = time_sig_str  # type: ignore[attr-defined]
    proxy.tempo_bpm = tempo_bpm  # type: ignore[attr-defined]
    proxy.total_sections = total_sections  # type: ignore[attr-defined]

    # Resolve generation groups
    generation_groups = _resolve_generation_groups(instrument_names, tracks, preset)

    # Per-group coherence state: keyed by group identifier
    group_coherence: dict[str, CoherenceState] = {}
    for group in generation_groups:
        gid = _group_identifier(group)
        group_coherence[gid] = CoherenceState.initial_from_analysis(proxy)

    # 7. Generate per section
    section_sources: list[str] = []
    json_sections: list[list[dict] | None] = []
    ticks_per_beat = analysis.ticks_per_beat

    # Import post-processing and beaming (lazy to avoid circular imports)
    from engrave.rendering.articulation import (
        apply_articulation_defaults,
        apply_section_consistency,
    )

    # Prepare audit log
    audit_log = AuditLog(job_id=output_dir or "")

    for sec_idx, boundary in enumerate(sections):
        start_bar = boundary.bar_number
        # End bar is either the next boundary's bar - 1, or total_bars
        if sec_idx + 1 < len(sections):
            end_bar = sections[sec_idx + 1].bar_number - 1
        else:
            end_bar = analysis.total_bars

        # Skip empty sections
        if end_bar < start_bar:
            json_sections.append(None)
            continue

        section_label = f"Section {sec_idx + 1}"
        logger.info("=== %s (bars %d-%d) ===", section_label, start_bar, end_bar)

        # a. Resolve beam_style for this temporal section
        from engrave.generation.section_groups import beaming_commands, resolve_beam_style

        section_description = None
        if audio_description is not None:
            for ad_section in audio_description.sections:
                if ad_section.start_bar <= end_bar and ad_section.end_bar >= start_bar:
                    section_description = getattr(ad_section, "style", None) or getattr(
                        ad_section, "texture", None
                    )
                    break

        beam_style = resolve_beam_style(
            section_description=section_description,
            user_hints=user_hints if user_hints else None,
        )
        beam_cmds = beaming_commands(beam_style)

        # b. Dispatch generation groups concurrently via asyncio.gather
        semaphore = asyncio.Semaphore(max_concurrent_groups)
        group_coros = [
            _process_group(
                group=group,
                coherence=group_coherence[_group_identifier(group)],
                sec_idx=sec_idx,
                start_bar=start_bar,
                end_bar=end_bar,
                ticks_per_beat=ticks_per_beat,
                beats_per_bar=beats_per_bar,
                time_sig_tuple=time_sig_tuple,
                key_sig=key_sig,
                tempo_bpm=tempo_bpm,
                beam_cmds=beam_cmds,
                section_label=section_label,
                router=router,
                compiler=compiler,
                rag_retriever=rag_retriever,
                audio_description=audio_description,
                user_hints=user_hints,
                semaphore=semaphore,
            )
            for group in generation_groups
        ]
        group_results: list[_GroupResult] = await asyncio.gather(*group_coros)

        # Collect results from all groups
        all_group_blocks: dict[str, str] = {}
        section_json_data: list[dict] | None = None
        section_had_fallback = False

        for gr in group_results:
            all_group_blocks.update(gr.blocks)
            if gr.used_fallback:
                section_had_fallback = True
            if gr.success and gr.updated_coherence is not None:
                group_coherence[gr.gid] = gr.updated_coherence
            if gr.json_data is not None:
                if section_json_data is None:
                    section_json_data = []
                section_json_data.extend(gr.json_data)

        # c. Log if any groups used rest fallback (pipeline continues)
        if section_had_fallback:
            logger.warning(
                "Section %d had rest fallback(s) -- some groups used rests",
                sec_idx,
            )

        # d. Apply post-processing: ENSM-03 defaults then ENSM-05 consistency
        processed_blocks: dict[str, str] = {}
        all_telemetry: list[dict] = []

        for var_name, content in all_group_blocks.items():
            processed, telemetry = apply_articulation_defaults(content)
            processed_blocks[var_name] = processed
            all_telemetry.extend(telemetry)

        if all_telemetry:
            logger.debug(
                "ENSM-03 staccato+accent resolutions: %d in section %d",
                len(all_telemetry),
                sec_idx,
            )

        # Apply ENSM-05 section consistency per generation group
        for group in generation_groups:
            if len(group) < 2:
                continue  # No consistency check for solo instruments
            group_parts: dict[str, str] = {}
            for name, _track in group:
                var_name = sanitize_var_name(name)
                if var_name in processed_blocks:
                    group_parts[var_name] = processed_blocks[var_name]
            if len(group_parts) >= 2:
                consistent_parts = apply_section_consistency(group_parts)
                processed_blocks.update(consistent_parts)

        # e. Build section source from processed blocks for all instruments
        var_declarations = []
        for name in instrument_names:
            var_name = sanitize_var_name(name)
            content = processed_blocks.get(var_name, all_group_blocks.get(var_name, "R1"))
            var_declarations.append(build_instrument_variable(var_name, content))

        section_source = _build_section_source(
            instrument_names, var_declarations, next(iter(group_coherence.values()))
        )

        section_sources.append(section_source)
        json_sections.append(section_json_data)

        # f. Build audit entry for this section
        section_audio_data: dict[str, str | None] = {
            "key": None,
            "tempo": None,
            "time_signature": None,
        }
        if audio_description is not None:
            section_audio_data["tempo"] = str(audio_description.tempo_bpm)
            section_audio_data["time_signature"] = audio_description.time_signature
            for ad_section in audio_description.sections:
                if ad_section.start_bar <= end_bar and ad_section.end_bar >= start_bar:
                    section_audio_data["key"] = ad_section.key
                    break

        resolutions: list[FieldResolution] = []
        for field_name in ("key", "tempo", "time_signature"):
            midi_val = {
                "key": key_sig,
                "tempo": str(tempo_bpm),
                "time_signature": time_sig_str,
            }[field_name]
            audio_val = section_audio_data.get(field_name)
            if audio_val is not None and audio_val:
                resolved = audio_val
                source = "audio"
            else:
                resolved = midi_val
                source = "midi"
            resolutions.append(
                FieldResolution(
                    field=field_name,
                    midi_value=midi_val,
                    audio_value=audio_val,
                    hint_value=None,
                    resolved_to=resolved,
                    source=source,
                )
            )
        audit_log.add_entry(
            section_index=sec_idx,
            section_label=section_label,
            resolutions=resolutions,
        )

        # g. Save training pair if output_dir is provided and JSON succeeded
        if output_dir is not None and section_json_data is not None:
            try:
                _save_training_pair(section_source, section_json_data, sec_idx, output_dir)
            except Exception:
                logger.warning("Failed to save training pair for section %d", sec_idx)

    # 8. Write audit log
    _write_audit_log(audit_log, output_dir)

    # 9. Assemble all sections
    if not section_sources:
        return GenerationResult(
            success=False,
            total_sections=total_sections,
            instrument_names=instrument_names,
            json_sections=json_sections,
        )

    assembled = assemble_sections(section_sources, instrument_names, analysis)

    # 10. Post-generation quality validation
    from engrave.generation.validation import validate_generation

    validation: ValidationResult | None = None
    try:
        validation = validate_generation(
            ly_source=assembled,
            original_midi_path=midi_path,
            instrument_names=instrument_names,
            compiler=compiler,
        )
        if validation.success:
            logger.info(
                "Validation: overall confidence %d%%",
                validation.overall_confidence_pct,
            )
            for part in validation.parts:
                logger.log(
                    logging.WARNING if part.needs_review else logging.INFO,
                    "  %s: %d%% match (F1=%.2f, drift=%.1f st)",
                    part.part_name,
                    part.confidence_pct,
                    part.f1,
                    part.pitch_drift_semitones,
                )
        else:
            logger.warning("Validation skipped: %s", validation.error)
    except Exception:
        logger.warning("Post-generation validation failed; continuing without it")

    return GenerationResult(
        success=True,
        ly_source=assembled,
        sections_completed=len(section_sources),
        total_sections=total_sections,
        instrument_names=instrument_names,
        json_sections=json_sections,
        validation=validation,
    )


# ---------------------------------------------------------------------------
# Helper: extract variable content from section source
# ---------------------------------------------------------------------------


def _extract_var_content(section_source: str, var_name: str) -> str:
    """Extract the music content for a variable from compiled section source.

    Looks for ``varName = { ... }`` and returns the inner content.
    """
    import re

    pattern = re.compile(
        rf"^{re.escape(var_name)}\s*=\s*\{{(.*?)\n\}}",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(section_source)
    if match:
        return match.group(1).strip()
    return "R1"


# ---------------------------------------------------------------------------
# Helper: render audio description text for a section
# ---------------------------------------------------------------------------


def _render_section_audio_text(
    audio_description: AudioDescription | None,
    sec_idx: int,
    start_bar: int,
    end_bar: int,
) -> str:
    """Render the audio description NL text for a section if available."""
    if audio_description is None:
        return ""

    from engrave.audio.templates import render_section_description, render_track_summary

    matched_section = None
    for ad_section in audio_description.sections:
        if ad_section.start_bar <= end_bar and ad_section.end_bar >= start_bar:
            matched_section = ad_section
            break

    parts: list[str] = []
    if sec_idx == 0:
        parts.append(render_track_summary(audio_description))
    if matched_section is not None:
        parts.append(render_section_description(matched_section))

    return "\n".join(parts) if parts else ""
