"""LilyPond structural template generation and LLM response parsing.

Generates valid LilyPond score skeletons with variable placeholders per
instrument. Uses absolute pitch mode (no \\relative) and concert pitch
(no \\transpose). The LLM fills in only music content within pre-validated
structural templates.
"""

from __future__ import annotations

import re

# Number word mapping for digits in instrument names
_NUMBER_WORDS = {
    "0": "Zero",
    "1": "One",
    "2": "Two",
    "3": "Three",
    "4": "Four",
    "5": "Five",
    "6": "Six",
    "7": "Seven",
    "8": "Eight",
    "9": "Nine",
}

# LilyPond built-in commands that clash with variable names when prefixed with \
_LILYPOND_RESERVED = frozenset(
    {
        "drums",
        "chords",
        "lyrics",
        "figures",
        "new",
        "score",
        "layout",
        "midi",
        "header",
        "paper",
        "book",
        "context",
        "voice",
        "staff",
        "tempo",
        "time",
        "key",
        "clef",
    }
)


def sanitize_var_name(instrument_name: str) -> str:
    """Convert instrument name to valid LilyPond variable name (camelCase).

    Examples:
        "Alto Sax 1" -> "altoSaxOne"
        "Trumpet in Bb" -> "trumpetInBb"
        "Electric Bass" -> "electricBass"
        "Drum Set" -> "drumSet"

    Args:
        instrument_name: Human-readable instrument name.

    Returns:
        A valid LilyPond identifier in camelCase.
    """
    # Replace digits with words
    result = instrument_name
    for digit, word in _NUMBER_WORDS.items():
        result = result.replace(digit, f" {word} ")

    # Split on spaces and non-alphanumeric characters
    words = re.split(r"[^a-zA-Z]+", result.strip())
    words = [w for w in words if w]  # Remove empties

    if not words:
        return "instrument"

    # camelCase: first word lowercase, rest capitalized
    parts = [words[0].lower()]
    for w in words[1:]:
        parts.append(w[0].upper() + w[1:] if len(w) > 1 else w.upper())

    name = "".join(parts)

    # Avoid LilyPond built-in commands (e.g. \drums, \chords, \lyrics)
    if name in _LILYPOND_RESERVED:
        name = name + "Part"

    return name


def build_score_template(
    instrument_names: list[str],
    section_label: str,
    start_bar: int,
    end_bar: int,
    beaming: str = "",
) -> str:
    """Generate complete LilyPond score skeleton with variable placeholders.

    Creates a valid LilyPond file structure with:
    - \\version "2.24.0" header
    - Comment with section label and bar range
    - One variable declaration per instrument
    - \\score block with \\new Staff for each instrument
    - ABSOLUTE pitch mode (no \\relative anywhere)
    - Concert pitch (no \\transpose anywhere)
    - Optional beaming commands injected at the start of the score block

    Args:
        instrument_names: List of instrument names (e.g., ["Trumpet", "Alto Sax"]).
        section_label: Section identifier (e.g., "A", "Verse").
        start_bar: First bar number in this section.
        end_bar: Last bar number in this section.
        beaming: Optional LilyPond beaming commands to inject at the start
            of the score block.  Empty string means no beaming override.

    Returns:
        Complete LilyPond source string with empty variable bodies to fill.
    """
    var_names = [sanitize_var_name(name) for name in instrument_names]

    # Build variable declarations
    variable_declarations = []
    for var_name in var_names:
        variable_declarations.append(f"{var_name} = {{\n  \n}}")

    variables_block = "\n\n".join(variable_declarations)

    # Build staff declarations
    staff_lines = []
    for var_name, inst_name in zip(var_names, instrument_names, strict=True):
        staff_lines.append(
            f'    \\new Staff \\with {{ instrumentName = "{inst_name}" }} \\{var_name}'
        )

    staves_block = "\n".join(staff_lines)

    # Build beaming block (injected after << in the score)
    beaming_block = ""
    if beaming:
        beaming_block = f"{beaming}\n"

    template = (
        f'\\version "2.24.0"\n'
        f"\n"
        f"% Generated by Engrave - concert pitch\n"
        f"% Section: {section_label} (bars {start_bar}-{end_bar})\n"
        f"\n"
        f"{variables_block}\n"
        f"\n"
        f"\\score {{\n"
        f"  <<\n"
        f"{beaming_block}"
        f"{staves_block}\n"
        f"  >>\n"
        f"  \\layout {{ }}\n"
        f"}}\n"
    )

    return template


def build_instrument_variable(var_name: str, music_content: str) -> str:
    """Format a single instrument variable with its music content.

    Args:
        var_name: Variable name (e.g., "trumpet").
        music_content: LilyPond music content to place inside.

    Returns:
        Formatted variable declaration string.
    """
    return f"{var_name} = {{\n  {music_content}\n}}"


def extract_variable_names(template: str) -> list[str]:
    """Parse a LilyPond template to find variable names the LLM must fill.

    Looks for patterns like ``varName = {`` in the template.

    Args:
        template: LilyPond template string.

    Returns:
        List of variable names found.
    """
    pattern = re.compile(r"^([a-zA-Z]\w*)\s*=\s*\{", re.MULTILINE)
    return pattern.findall(template)


def strip_variable_wrapper(var_name: str, content: str) -> str:
    """Strip a redundant ``varName = { ... }`` wrapper from LLM-generated content.

    LLMs often echo back the template wrapper even though the pipeline adds its
    own via :func:`build_instrument_variable`.  This function detects and removes
    the outer wrapper so the content can be re-wrapped cleanly.

    Also strips leading ``% varName: ...`` comment lines that some LLMs emit.

    Args:
        var_name: The expected variable name (e.g. "trumpets").
        content: Raw content string that may contain a wrapper.

    Returns:
        Inner music content with wrapper removed, or original content if no
        wrapper detected.
    """
    # Strip leading comment lines like "% varName: trumpets" or "% varName"
    cleaned = re.sub(
        r"^%\s*varName[:\s].*\n*",
        "",
        content,
        flags=re.MULTILINE,
    ).strip()

    # Strip outer varName = { ... } wrapper
    wrapper_pattern = re.compile(
        rf"^\s*{re.escape(var_name)}\s*=\s*\{{(.*)\}}\s*$",
        re.DOTALL,
    )
    match = wrapper_pattern.match(cleaned)
    if match:
        return match.group(1).strip()

    return cleaned


def parse_instrument_blocks(llm_response: str) -> dict[str, str]:
    """Parse labeled instrument blocks from LLM output.

    Expects blocks formatted as::

        % varName
        ...music content...

        % anotherVar
        ...music content...

    Also handles ``varName = { ... }`` blocks as a fallback.
    Blocks are separated by blank lines or the next ``% varName`` marker.

    Args:
        llm_response: Raw LLM response text.

    Returns:
        Dict mapping variable name to music content string.

    Raises:
        ValueError: If no instrument blocks found.
    """
    # Find all blocks starting with % varName
    block_pattern = re.compile(
        r"^%\s+(\w+)\s*\n(.*?)(?=^%\s+\w+|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    matches = block_pattern.findall(llm_response)

    if not matches:
        # Fallback: try varName = { ... } blocks
        var_block_pattern = re.compile(
            r"^([a-zA-Z]\w*)\s*=\s*\{(.*?)\n\}",
            re.MULTILINE | re.DOTALL,
        )
        var_matches = var_block_pattern.findall(llm_response)
        if var_matches:
            result: dict[str, str] = {}
            for var_name, content in var_matches:
                result[var_name] = content.strip()
            return result

        raise ValueError(
            "No instrument blocks found in LLM response. Expected format: '% varName\\n...music...'"
        )

    result = {}
    for var_name, content in matches:
        result[var_name] = content.strip()

    return result
