"""Unit tests for per-measure surgical re-generation."""

from __future__ import annotations

import pytest

from engrave.generation.measure_fix import (
    _build_measure_fix_prompt,
    _extract_variable,
    _splice_variable,
)

# --- Sample LilyPond source for testing ---

SAMPLE_LY = r"""
\version "2.24.0"

% Generated by Engrave - concert pitch

global = {
  \key c \major
  \time 4/4
  \tempo 4 = 120
}

trumpetOne = {
  c'4 d'4 e'4 f'4 |
  g'4 a'4 b'4 c''4 |
  d''2 r2 |
}

altoSaxOne = {
  e'4 f'4 g'4 a'4 |
  b'4 c''4 d''4 e''4 |
}

\score {
  <<
    \new Staff \with { instrumentName = "Trumpet" } { \global \trumpetOne }
    \new Staff \with { instrumentName = "Alto Sax" } { \global \altoSaxOne }
  >>
  \layout { }
}
""".strip()


class TestExtractVariable:
    def test_extracts_trumpet(self):
        result = _extract_variable(SAMPLE_LY, "trumpetOne")
        assert result is not None
        content, start, end = result
        assert "c'4 d'4 e'4 f'4" in content
        assert "g'4 a'4 b'4 c''4" in content
        assert start > 0
        assert end > start

    def test_extracts_alto_sax(self):
        result = _extract_variable(SAMPLE_LY, "altoSaxOne")
        assert result is not None
        content, _, _ = result
        assert "e'4 f'4 g'4 a'4" in content

    def test_missing_variable_returns_none(self):
        result = _extract_variable(SAMPLE_LY, "nonExistent")
        assert result is None

    def test_does_not_extract_global(self):
        # global is a special block, not an instrument variable
        result = _extract_variable(SAMPLE_LY, "global")
        assert result is not None  # It should still find it syntactically


class TestSpliceVariable:
    def test_splice_replaces_content(self):
        new_content = "c'2 d'2 | e'1 | f'2 r2 |"
        result = _splice_variable(SAMPLE_LY, "trumpetOne", new_content)
        assert "c'2 d'2 | e'1 | f'2 r2 |" in result
        # Original content should be gone
        assert "c'4 d'4 e'4 f'4" not in result
        # Other variable should be untouched
        assert "e'4 f'4 g'4 a'4" in result

    def test_splice_nonexistent_raises(self):
        with pytest.raises(ValueError, match="nonExistent"):
            _splice_variable(SAMPLE_LY, "nonExistent", "R1")


class TestBuildPrompt:
    def test_prompt_contains_key_elements(self):
        prompt = _build_measure_fix_prompt(
            instrument_name="Trumpet",
            var_content="c'4 d'4 e'4 f'4 | g'4 a'4 b'4 c''4",
            bar_number=2,
            user_hint="rhythm should be dotted quarter, eighth, half",
        )
        assert "bar" in prompt.lower() or "Bar" in prompt
        assert "2" in prompt
        assert "Trumpet" in prompt
        assert "dotted quarter" in prompt
        assert "c'4 d'4 e'4 f'4" in prompt
